Reverse the sub Array
neerajnanvani/PracticeGitAndJs pull request #48
Opened 2022-12-14 15:19 UTC by neetu1123

Reverse the sub array of group in .ts file with some strict type

2022-12-14 15:20 UTC, neetu1123 commented
close #48 reverse the group of sub array

2022-12-15 03:39 UTC, neerajnanvani requested changes

2022-12-15 03:39 UTC, neerajnanvani commented on index.html
> +</html>
delete this file

2022-12-15 03:39 UTC, neerajnanvani commented on script.js
> +             str =arr[i]
delete this file

2022-12-15 03:39 UTC, neerajnanvani commented on script.ts
> +             console.log(arr)
remove console

2022-12-15 04:14 UTC, neetu1123 commented
updated close #48

2022-12-15 04:33 UTC, neetu1123 commented
i had closed by mistake , i am reopening it

2022-12-15 08:29 UTC, neerajnanvani requested changes

2022-12-15 08:29 UTC, neerajnanvani commented on script.ts
> +        reverseArr(arr,index) // return reverse sub array
this answer doesn't give me correct outputs in different arrays and different key

2022-12-15 09:45 UTC, neerajnanvani commented on script.ts
> +       const reverseArr= (arr,index) => {
give types to arr and index parameters

2022-12-15 11:57 UTC, neerajnanvani commented on script.ts
> +        while (start < end) {
start number is undefined

2022-12-20 04:11 UTC, neetu1123 commented
closed

2023-01-09 03:59 UTC, closed without merging